/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 panther.glb
Author: ThreeStretch (https://sketchfab.com/ThreeStretch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-panther-2-b313e4f9c6a54129a9420f8f1873c71e
Title: Black Panther 2
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Panther = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/panther.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="OSG_Scene_76" scale={10}>
                <group name="RootNode_(gltf_orientation_matrix)_75" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="RootNode_(model_correction_matrix)_74">
                    <group name="8fc75cd612a84b67b9acf9fbc91cf238fbx_73" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="_72">
                        <group name="RootNode_71">
                          <group name="_70">
                            <group name="GLTF_created_0">
                              <primitive object={nodes.GLTF_created_0_rootJoint} />
                              <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material__25_0mat} skeleton={nodes.Object_13.skeleton} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/panther.glb')

export default Panther
